// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2D2q6dOyERPX4dbbm5JQ9wTDq9nj8IFY',
    appId: '1:1019757130341:web:18d06be4e5328b871ecc8c',
    messagingSenderId: '1019757130341',
    projectId: 'ghhhhhhhhgjgjgjrfkfc',
    authDomain: 'ghhhhhhhhgjgjgjrfkfc.firebaseapp.com',
    storageBucket: 'ghhhhhhhhgjgjgjrfkfc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJC0PTB308uLnSu1JQ4elDn0GFHaRT4Cs',
    appId: '1:1019757130341:android:6a796665f9e5d3d61ecc8c',
    messagingSenderId: '1019757130341',
    projectId: 'ghhhhhhhhgjgjgjrfkfc',
    storageBucket: 'ghhhhhhhhgjgjgjrfkfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCATS_-ws2D2X8DO7meCUmO-QIr1JJGNQw',
    appId: '1:1019757130341:ios:aab70d8bad7a187e1ecc8c',
    messagingSenderId: '1019757130341',
    projectId: 'ghhhhhhhhgjgjgjrfkfc',
    storageBucket: 'ghhhhhhhhgjgjgjrfkfc.appspot.com',
    iosClientId: '1019757130341-fa9dha6tr0f5i3prr199fdtfb0immgai.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCATS_-ws2D2X8DO7meCUmO-QIr1JJGNQw',
    appId: '1:1019757130341:ios:c2880e9814d2e7db1ecc8c',
    messagingSenderId: '1019757130341',
    projectId: 'ghhhhhhhhgjgjgjrfkfc',
    storageBucket: 'ghhhhhhhhgjgjgjrfkfc.appspot.com',
    iosClientId: '1019757130341-fbof6e41ihhq2airrudruo5jk5qpj259.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeServices.RunnerTests',
  );
}
